# Generated by Django 4.2.5 on 2023-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
